### ISSUE TITLE
Forgerock Identity Cloud - Import / Export of CORS seetings

### ISSUE THREAD

**Issue by JavaLudwig** [rockcarver/frodo-cli#101]
Additional functionality as to importing / exporting CORS settings from the Teanant settings in ForgeRock Identity Cloud.

**Comment by vscheuber** [comment]
@atomicsamurai totally agree we should do this. I wonder if we need to re-think how we organize our commands. CORS settings are cloud-only, like ESVs and logging. There is currently no easy way for an admin to find out which command is available for which backend. Let's discuss how we can best address this. Gonna file an RFE specifically for that purpose.
