### ISSUE TITLE
Adding Feature for Importing Cert to Frodo Truststore

### ISSUE THREAD

**Issue by raydeng83** [rockcarver/frodo-cli#113]
We are facing an issue when using self-cert in ForgeRock AM. The error message goes:

**Error getting cookie name: Error: self-signed certificate in certificate chain
error authenticating - self-signed certificate in certificate chain**

This happens when connecting to AM. Unfortunately, the corp policy requires to use TLS and our own CA. So it would be great to add this feature to unblock us from going forward. Thanks.

Best,
Le

**Comment by atomicsamurai** [comment]
You can specify `-k, --insecure` flag with most sub-commands, which will bypass the validation of the certificate trust chain. This should not be a cause for concern for this case as the service you are connecting to (AM/IDM REST) is managed by you and you know that there is no man in the middle impersonating those servers.

**Comment by raydeng83** [comment]
Thanks Sandeep. 

We have a slightly different use case. We put a java wrapper around Frodo and deploy it as a service, so that it can be called by other apps to import/export journeys.

NodeJS has a way to specify truststore file as a environment variable, which should resolve the cert trusting issue. Thanks for the info anyways.
