### ISSUE TITLE
application import -f will not support import of multiple files (folder or wildcard)

### ISSUE THREAD

**Issue by rjackson-fr** [rockcarver/frodo-cli#120]
## Frodo CLI version
You seem to be running the binary package
Installed versions:
cli: v0.18.1
lib: v0.16.1
node: v18.5.0

## Describe the issue
frodo application import -f ./folder tenant alpha
ForgeRock Identity Cloud detected.
Connected to ForgeRock Access Management 7.3.0-2022-8-SNAPSHOT Build a05ac3729caa18bbb3caff4730d3392600a1500b (2022-September-23 12:38)
Importing OAuth2 application(s) ...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}

frodo application import -f ./folder/*.json tenant alpha
Error getting cookie name: Error: connect ECONNREFUSED ::1:80
error authenticating - Invalid value "undefined" for header "X-OpenAM-Password"
/snapshot/dist/src/utils/Console.js:131
    console.error(message['brightRed']);
                         ^

TypeError: Cannot read properties of undefined (reading 'brightRed')
    at error (/snapshot/dist/src/utils/Console.js:131:26)
    at printMessage (/snapshot/dist/src/utils/Console.js:205:7)
    at printMessage (/snapshot/dist/node_modules/@rockcarver/frodo-lib/cjs/ops/utils/Console.js:41:5)
    at /snapshot/dist/node_modules/@rockcarver/frodo-lib/cjs/ops/AuthenticateOps.js:284:35
    at Generator.throw (<anonymous>)
    at asyncGeneratorStep (/snapshot/dist/node_modules/@rockcarver/frodo-lib/cjs/ops/AuthenticateOps.js:36:103)
    at _throw (/snapshot/dist/node_modules/@rockcarver/frodo-lib/cjs/ops/AuthenticateOps.js:38:291)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

frodo application import -f ./folder/\*.json tenant alpha
ForgeRock Identity Cloud detected.
Connected to ForgeRock Access Management 7.3.0-2022-8-SNAPSHOT Build a05ac3729caa18bbb3caff4730d3392600a1500b (2022-September-23 12:38)
Importing OAuth2 application(s) ...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, open './folder/*.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './alpha/*.json'
}

**Comment by vscheuber** [comment]
We should add support for `-a` and `-A` to the `app` command.

**Comment by vscheuber** [comment]
This has been fixed recently in the 2.x (main) branch. Beware the `app` command has been renamed to `oauth` and `app` is now used for the new applications introduced with workforce and IGA.
