### ISSUE TITLE
Create new service command to expose contributed AM service management capabilty

### ISSUE THREAD

**Issue by vscheuber** [rockcarver/frodo-cli#127]
@mhjmaas contributed AM service functionality to frodo-lib in https://github.com/rockcarver/frodo-lib/pull/152 which needs a reference usage implementation here in frodo-cli.

**Comment by mhjmaas** [comment]
@vscheuber Isn't [this pull request](https://github.com/rockcarver/frodo-cli/pull/118) the reference usage implementation you are speaking of?

**Comment by vscheuber** [comment]
@mhjmaas ha! Yes it is! I did not see that or was looking in my fork instead of the main repo! Great!!
