### ISSUE TITLE
Describe ESV - when returning a URL, doesn't display correctly.

### ISSUE THREAD

**Issue by bradt-fr** [rockcarver/frodo-cli#151]
ESV value stored in FIDC:
https://login.salesforce.com/services/oauth2/token

Using:

`frodo esv variable describe -i esv-endpoint-uri https://tenant.forgeblocks.com/am`

Returns:

Describing variable esv-endpoint-uri...
Name         │esv-sf-token-endpoint-uri
Value        │gin.salesforce.com/services/oauth2/token
<remainder redacted>

**Comment by atomicsamurai** [comment]
Looks like the word wrapping logic is causing this. I will look into this.
