### ISSUE TITLE
Use Frodo for Services

### ISSUE THREAD

**Issue by aphillipo** [rockcarver/frodo-cli#156]
Hi there! 

Thanks so much for Frodo it's definitely streamlining our deployment of Forgerock.

We need to be able to set a value in "services" programmatically but we can't do that until 0.18.2 is released!

If you have any timescale for this, it would be great to know. Thanks!

**Comment by vscheuber** [comment]
@aphillipo thank you for reaching out! `0.18.2` (or more likely `0.19.0`) is expected to release shortly.

Just to clarify: You have access to the pre-releases. When doing an npm install, use `npm i -g @rockcarver/frodo-cli@next` to install the latest pre-release.

Currently the only difference between a pre-release and an official release is a curated changelog and test coverage. I would actually appreciate if you could run the pre-release and let me know if it works for your services use case.

**Comment by aphillipo** [comment]
I can get the info from services just fine, I haven't tested setting it yet. Let me test that now! Glad to hear 0.19.0 isn't too far away.

**Comment by aphillipo** [comment]
Works perfectly! Thank you!

**Comment by vscheuber** [comment]
@aphillipo we release Frodo CLI 0.19.0 over the weekend.
