### ISSUE TITLE
Support for Linux AARCH 64(ARM chipset)

### ISSUE THREAD

**Issue by debasisdwivedy** [rockcarver/frodo-cli#166]
## Frodo CLI version
Provide cli executable for linux AARCH 64(arm chipset)

## Describe the issue
The current cli for linux support x86/amd architecture. When run on linux with a arm(AARCH 64) chipset the below error occurs:

`Importing tree to realm:/
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`

This is because the current jdk required for the executable is based on x84-64/amd. 
To make it comparable with linux with a arm(AARCH 64) the jdk used should be of AARCH 64.

The mac version of the executable does not work on linux

**Comment by vscheuber** [comment]
@debasisdwivedy can you elaborate what hardware platform you are wanting to use and which linux distro you are running? I'm looking into what it would take for us to add an AARCH64 build.

**Comment by vscheuber** [comment]
@debasisdwivedy I managed to have our pipeline produce an arm64 build in the latest pre-release:

https://github.com/rockcarver/frodo-cli/releases/tag/v0.19.3-1

Look for the file [frodo-linux-arm64-0.19.3-1.zip](https://github.com/rockcarver/frodo-cli/releases/download/v0.19.3-1/frodo-linux-arm64-0.19.3-1.zip) and give it a try. Let me know how that works for you.

I'll have to discuss with the team if we want to permanently add arm64 as a platform. Therefore I am still curious as to what hardware and distro you are running.

**Comment by debasisdwivedy** [comment]
Hi @vscheuber ,

Thanks for the executable. I will give it a detailed try but from initial run it appears to be working.

The architecture is as below:
`am@forgerock-access-manager-az1-0:/$ uname -a
Linux forgerock-access-manager-az1-0 5.15.49-linuxkit #1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022 aarch64 GNU/Linux
am@forgerock-access-manager-az1-0:/$ 
am@forgerock-access-manager-az1-0:/$ 
am@forgerock-access-manager-az1-0:/$ 
am@forgerock-access-manager-az1-0:/$ uname -m
aarch64
`

We are running Debian(bullseye) OS on AARCH 64/arm64 processor on Amazon(AWS).

I think given the progress made by arm chips it would be a good addition. Moreover MacOS runs on ARM (the M series).


Have a great new year.

Regards,
Debasis

**Comment by vscheuber** [comment]
I'm closing this for now. The team still has to concluded definitively how we are going to build this but for now my arm-based dev board will do the building. Maybe (hopefully!) in the future GitHub will provide arm runners we can use instead.

**Comment by atomicsamurai** [comment]
You can now install frodo with homebrew (https://github.com/rockcarver/frodo-cli#quick-start), so if your arm based host has homebrew, this is the recommended way. Disclaimer: For now, I have only tested frodo from homebrew on x86 linux and M1 Mac.
