### ISSUE TITLE
Not able to export journeys from sub realms for macos binary

### ISSUE THREAD

**Issue by debasisdwivedy** [rockcarver/frodo-cli#170]
## Frodo CLI version
Provide output of `frodo -v`

## Describe the issue
Linux binary works fine and the issue is with mac binary. I am using mac M1.
We are trying to export journeys from a sub-realm as below:
`./frodo journey export http://am.example.com/openam /realm/subrealm 'amadmin' 'Password123' -m classic -A`

and getting an exception as below:

`Connected to ForgeRock Access Management 7.1.2 Build 1b8a956b868a6794e652f23a878e694c07b8ecc9 (2022-March-11 20:06)
Exporting all journeys to separate files...
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "AxiosError: Request failed with status code 404".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.5.0`

The command works fine for root realms like /realm1 and /realm2 but fails to export trees for its sub-realms.

Amtree tool is able to extract the journeys from sub realms. The command is as below:
`./amtree.sh -h http://am.example.com/openam -u amadmin -p Password123 -r /realm/subrealm -S -n -m Classic`

For reference i am using frodo macOS binary

`v0.10.4 [v18.5.0]`

Regards

**Comment by vscheuber** [comment]
@debasisdwivedy I believe this to be a duplicate of rockcarver/frodo-lib#100 , which was fixed in 0.13.2. You seem to be running a fairly old version. Would you mind downloading a more recent binary for MacOS and giving it a try?

**Comment by debasisdwivedy** [comment]
Thanks @vscheuber . Yes it was an old version
