### ISSUE TITLE
logs tail produce non-json output at times.

### ISSUE THREAD

**Issue by patrickdiligentforgerock** [rockcarver/frodo-cli#184]
cli: v0.19.3
lib: v0.17.5
node: v18.5.0

At times this command: 

frodo logs tail -c idm-everything -L ALL <con> produces traces like this:

```
"Jan 17, 2023 2:52:23 AM org.forgerock.openidm.util.LogUtil logAtLevel"
"INFO: Scheduled service \"scheduler-service-group.LiveSyncEksDJ\" invoke completed successfully."

```

However, using curl against the logging endpoint `/monitoring/logs/tail?source=idm-everything` shows properly formatted JSON for these traces:

```
{
            "payload": "Jan 17, 2023 5:09:08 AM org.forgerock.openidm.util.LogUtil logAtLevel",
            "timestamp": "2023-01-17T05:09:08.186263792Z",
            "type": "text/plain",
            "source": "idm-core"
        }
```

**Comment by atomicsamurai** [comment]
@patrickdiligentforgerock frodo outputs the `payload` from the log messages. IDM debug logs' payload is not JSON (just plain text) and that is why those are logged as text. Other log types, where the payload is JSON, frodo outputs JSON. There is a jira for addressing this in ID Cloud: FRAAS-11296.

**Comment by patrickdiligentforgerock** [comment]
@atomicsamurai how do you explain the logging endpoint wraps the plain text in JSON, while frodo does not?

**Comment by patrickdiligentforgerock** [comment]
To support further the case, this trace in an onUpdate script:

```
function _tag(message){
    return `${config.nodeName}:: ${message}`;
  }
  
  logger.error(_tag("request : " + request));
```
WITH frodo:

```
"SEVERE: alpha_user-onUpdate:: request : { \"patchOperations\": [ { \"operation\": \"replace\", \"field\": \"/description\", \"value\": \"That\" } ], \"method\": \"patch\", \"resourcePath\": \"\", \"additionalParameters\": {  }, \"fields\": [  ], \"revision\": \"9b90b88b-fcfb-43b9-9ec1-7b78f414e2c9-8222\" }"
"SEVERE: alpha_user-onUpdate:: request : { \"patchOperations\": [ { \"operation\": \"replace\", \"field\": \"/description\", \"value\": \"That\" } ], \"method\": \"patch\", \"resourcePath\": \"\", \"additionalParameters\": {  }, \"fields\": [  ], \"revision\": \"9b90b88b-fcfb-43b9-9ec1-7b78f414e2c9-8222\" }"
```
[ Not that it is repeated twice ]

WITH `GET /monitoring/logs/tail?source=idm-everything&_prettyPrint=true`

```
    {
            "payload": "SEVERE: alpha_user-onUpdate:: request : { \"patchOperations\": [ { \"operation\": \"replace\", \"field\": \"/description\", \"value\": \"That\" } ], \"method\": \"patch\", \"resourcePath\": \"\", \"additionalParameters\": {  }, \"fields\": [  ], \"revision\": \"9b90b88b-fcfb-43b9-9ec1-7b78f414e2c9-8222\" }",
            "timestamp": "2023-01-17T23:19:53.898162358Z",
            "type": "text/plain",
            "source": "idm-core"
        },
```
```

**Comment by atomicsamurai** [comment]
Exactly my point - the logging endpoint returns the actual message, which is:

```
"SEVERE: alpha_user-onUpdate:: request : { \"patchOperations\": [ { \"operation\": \"replace\", \"field\": \"/description\", \"value\": \"That\" } ], \"method\": \"patch\", \"resourcePath\": \"\", \"additionalParameters\": {  }, \"fields\": [  ], \"revision\": \"9b90b88b-fcfb-43b9-9ec1-7b78f414e2c9-8222\" }"
```

wrapped in a JSON envelope. frodo just does not show the envelope, only the "payload". Are you saying that frodo should output the complete JSON? Sorry if I misunderstand.

**Comment by patrickdiligentforgerock** [comment]
@atomicsamurai - Yes - exactly the point. In fact why is 'fetch' wrapping into a JSON object and not 'tail', while the monitoring endpoints have a consistent JSON format?

This is actually awkward, as for example, in troubleshooting, it's common to pipe the frodo command to jq, however, having non JSON in the mix is complicating things. And since the format differs, with 'fetch' for example I would select the  key ".payload.transactionId", but that becomes ".transactionId" for 'tail', adding further awkwardness.

Also it completes the task when leveraging the lib to develop a feed to an external logging service.

**Comment by vscheuber** [comment]
@atomicsamurai I believe this was fixed, wasn't it? @patrickdiligentforgerock is this still an issue?

**Comment by vscheuber** [comment]
Closing.
