### ISSUE TITLE
Allow ESV variables to be created of a non-string type

### ISSUE THREAD

**Issue by DannyBlazejczak** [rockcarver/frodo-cli#194]
ForgeRock supports multiple ESV types as documented here:
https://backstage.forgerock.com/docs/idcloud/latest/tenants/esvs.html

Currently it only supported the 'string' type.

An ESV of array type could be created with this curl command:
`
curl --location --request PUT 'https://openam-atlas.forgeblocks.com/environment/variables/esv-testarray' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/110.0' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Accept-Language: en-US,en;q=0.5' \
--header 'Accept-Encoding: gzip, deflate, br' \
--header 'Referer: https://openam-atlas.forgeblocks.com/' \
--header 'content-type: application/json' \
--header 'accept-api-version: protocol=1.0,resource=1.0' \
--header 'Authorization: Bearer <TOKEN>' \
--header 'Origin: https://openam-atlas.forgeblocks.com'/ \
--header 'Connection: keep-alive' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-origin' \
--header 'TE: trailers' \
--data-raw '{"description":"","valueBase64":"WyJvbmUiLCJ0d28iXQo=","expressionType":"array"}'
`

This enhancement request is to have the expressionType also supported in the ESV command line, while defaulting to a string as per current behavior.
e.g.
`
frodo esv variable create --variable-id "esv-name" --value "["1","2"]" --expression-type array am realm; 
`

**Comment by vscheuber** [comment]
Completed on July 18, 2023.

`frodo variable create` now supports the `--variable-type [variable-type]` option. Must be one of "string", "list", "array", "object", "bool", "int", or "number". (default: "string")

Command help output includes usage examples:

**Comment by vscheuber** [comment]
Completed on July 18, 2023.

`frodo variable create` now supports the `--variable-type [variable-type]` option. Must be one of "string", "list", "array", "object", "bool", "int", or "number". (default: "string")

Command help output includes usage examples:
```bash
Usage Examples:
  Create an ESV variable using implied default type "string":
  $ frodo esv variable create --variable-id "esv-trinity-phone" --value "(312)-555-0690" --description "Trinity's phone number." matrix
  Create an ESV variable of type "array":
  $ frodo esv variable create --variable-id "esv-nebuchadnezzar-crew" --variable-type array --value '["Morpheus","Trinity","Link","Tank","Dozer","Apoc","Cypher","Mouse","Neo","Switch"]' --description "The crew of the Nebuchadnezzar hovercraft." matrix
  Create an ESV variable of type "object":
  $ frodo esv variable create --variable-id "esv-nebuchadnezzar-crew-structure" --variable-type object --value '{"Captain":"Morpheus","FirstMate":"Trinity","Operator":["Link","Tank"],"Medic":"Dozer","Crewmen":["Apoc","Cypher","Mouse","Neo","Switch"]}' --description "The structure of the crew of the Nebuchadnezzar hovercraft." matrix
  Create an ESV variable of type "int":
  $ frodo esv variable create --variable-id "esv-neo-age" --variable-type int --value '28' --description "Neo's age in the matrix." matrix
  Create an ESV variable of type "bool":
  $ frodo esv variable create --variable-id "esv-blue-piller" --variable-type bool --value 'false' --description "Zion membership criteria." matrix
```
