### ISSUE TITLE
Unable to export all Journeys to a specfic folder

### ISSUE THREAD

**Issue by rclapman** [rockcarver/frodo-cli#198]
frodo -v
A new version of frodo is available.
Please run 'frodo -v' for more details.
You seem to be running the NPM package
Installed versions:
cli: v0.19.4
lib: v0.17.6
node: v18.13.0

Newer version(s) available
cli (npm): v0.21.1

## Describe the issue
Tried this command
frodo journey export -D frodo/clapman -A clapman

and it puts it under root dir

**Comment by vscheuber** [comment]
Hi @rclapman , a similar request was placed a while ago but has not yet been implemented: rockcarver/frodo-lib#26

**Comment by vscheuber** [comment]
Fixed in frodo-cli v2.0.0-23 and later.
