### ISSUE TITLE
ES Module loading with absolute path fails on windows

### ISSUE THREAD

**Issue by cmcneilniu** [rockcarver/frodo-cli#212]
## Frodo CLI version
Version: v0.23.0
Platform: Windows 10 64-bit
Node: v16.16.0
What steps will reproduce the bug?
After installed frodo, input any frodo command e.g. 'frodo help' 'frodo -v'  

## Describe the issue
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
![image](https://user-images.githubusercontent.com/80231313/223888406-20fed4d4-b8e8-49bd-8064-0b8e77e3011c.png)

**Comment by vscheuber** [comment]
Hi @cmcneilniu , did you install the frodo binary or the NPM version?

The NPM version can be a bit tricky at times and honestly I never used it on Windows. The binary (.exe) wraps it all into one nice package and you should never run into any of these types of issues.

In case you must run the NPM version, I will try to help you figure out what's happening here. I'm currently traveling but will look into it as soon as I can.

**Comment by vscheuber** [comment]
@cmcneilniu would you like me to look further into this or did you find a solution?

**Comment by cmcneilniu** [comment]
Hi @vscheuber, yes please look further into this. I have to use NPM version. From my understanding, update the absolute path could be a fix.

**Comment by jgdtech** [comment]
+1 on this one. Can't use NPM version in git bash because of this bug. Admins lock things down so that binaries can't be installed (deletes new binaries that show up in filesystem too) without approval - npm and node are approved of course.

**Comment by vscheuber** [comment]
@cmcneilniu and @jgdtech I have not been able to reproduce this in the latest 1.x and 2.x versions. I never saw this issue so I am not sure if my env is immune to it and it's still lurking out there or has been addressed? We have made several changes that could have resolved this for Windows but I really don't know for sure. Please re-open if this is still an issue for you.
