### ISSUE TITLE
Frodo CLI exits with code 0 in the case that an error occurs when calling the underlying FR API.

### ISSUE THREAD

**Issue by zya** [rockcarver/frodo-cli#214]
## Frodo CLI version
0.23.0

## Describe the issue
Frodo CLI exits with code 0 in the case that an error occurs when calling the underlying FR API.
For example, if the application config file contain invalid configuration, and FR returns a 400. 
This might be because of the way errors are handled in [calls to FR here](https://github.com/rockcarver/frodo-cli/blob/main/src/ops/IdmOps.ts#L259-L283). 
The errors are caught and logged but not returned again.

**Comment by vscheuber** [comment]
@zya thank you for this report! Yes, we are painfully aware of this situation. We have started to introduce -1 return codes for commands we recently modified but it is not consistent, yet, and there is still a lot to do.

I'll definitely work on this but also welcome any help you are willing to render. If you are a developer and would like to help: please put up a PR :)
