### ISSUE TITLE
Insecure flag doesn't work on various commands

### ISSUE THREAD

**Issue by jgdtech** [rockcarver/frodo-cli#215]
## Frodo CLI version
Provide output of `frodo -v`
You seem to be running the NPM package
Installed versions:
cli: v0.22.3
lib: v0.18.7
node: v18.14.0

## Describe the issue
Passing -k or --insecure to various commands doesn't work.

AMURL=https://openam-xxxxxx1-staging.id.forgerock.io/am
Examples: 
$ frodo info -k $AMURL
Error getting cookie name: Error: self-signed certificate in certificate chain
Service account login error: Error: self-signed certificate in certificate chain

I will attach log of frodo info -k --debug --curlirize $AMURL - the curl commands don't have --insecure or -k in them

**Comment by jgdtech** [comment]
Beginning output of the --k --debug --curlirize command mentioned above... Note that the curl doesn't have -k or --insecure as expected when passing -k:

FrodoCommand.handleDefaultArgsAndOpts: Handling default option 'curlirize'.
AuthenticateOps.getTokens: start
curl -X GET -H "User-Agent:@rockcarver/frodo-lib/0.18.7" -H "X-ForgeRock-TransactionId:frodo-16c1f3b9-5bf2-409e-8284-fe34b72e8a48" -H "Content-Type:application/json" -H "Accept-API-Version:resource=1.1" "https://openam-cut-staging.id.forgerock.io/am/json/serverinfo/*"certificate chain
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12)
AuthenticateOps.getTokens: Authenticating with service account -cut-
AuthenticateOps.getAccessTokenForServiceAccount: start
AuthenticateOps.getAccessTokenForServiceAccount: payload:
{
  iss: '-cut-',
  sub: '-cut-',
  aud: 'https://openam-cut-staging.id.forgerock.io:443/am/oauth2/access_token',
  exp: 1678740244,
  jti: '13af8361-7ff8-445a-98c7-1a62eb5ef12c'
}
AuthenticateOps.getAccessTokenForServiceAccount: jwt:
-cut-
curl -X POST -H "Content-Type:application/x-www-form-urlencoded" -H "User-Agent:@rockcarver/frodo-lib/0.18.7" -H "X-ForgeRock-TransactionId:frodo-16c1f3b9-5bf2-409e-8284-fe34b72e8a48" -H "Accept-API-Version:protocol=2.1,resource=1.0" --data 'assertion=-cut-&client_id=service-account&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&scope=fr:am:* fr:idm:* fr:idc:esv:*' "https://openam-cut-staging.id.forgerock.io/am/oauth2/access_token"
    at TLSSocket._finishInit (node:_tls_wrap:959:8)
    at ssl.onhandshakedone (node:_tls_wrap:743:12) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN',

**Comment by jgdtech** [comment]
I tried all the way back to frodo v0.20.0, same issue.

**Comment by vscheuber** [comment]
@jgdtech I will look into this one. I am not sure why this would be broken. The `-k` flag works globally but in all fairness, I haven't used it in a long while! Let me revisit and see if a recent code change may have broken it!

I have worked with a company who did exactly the same as you ended up doing. They were using frodo-lib, though, and created their own wrapper for it, so they were no limited by the binary executable.

We should probably document this approach, as it is really helpful for proxy envs.

**Comment by vscheuber** [comment]
@jgdtech one more comment on this one: the `--curlirize` option may not be aware of the `-k` option at the moment. So the curl commands generated by `--curlirize` are not an indicator of the `-k` option working or not working.

**Comment by vscheuber** [comment]
I believe this not to be a frodo issue. Several parties have run into similar issues and they were all caused by proxies or "ssl interceptors" and it is not frodo's responsibility to account for those. We might consider to document the common [solution](https://github.com/rockcarver/frodo-cli/issues/215#issuecomment-1480165473) in multiple instances.
