### ISSUE TITLE
Consistent arg name handling

### ISSUE THREAD

**Issue by CharanMann** [rockcarver/frodo-cli#23]
Currently some args names are optional and others are mandatory, refer below: 

- No arg name for host: ./frodo logs tail -c idm-everything -l DEBUG  openam-ps.forgeblocks.com 
- No arg name for host, user, password, key, secret: ./frodo connections add https://openam-ps.forgeblocks.com/am john.doe@example.com passwordddddd keyyyyy secrettt 

These args should be passed with arg names such as:
- ./frodo logs tail -c idm-everything -l DEBUG  -h openam-ps.forgeblocks.com (No arg name for host)
- ./frodo connections add -h https://openam-ps.forgeblocks.com/am -u john.doe@example.com -p passwordddddd -k keyyyyy -s secrettt  

This will avoid any confusion regarding these args handling

**Comment by atomicsamurai** [comment]
Testing slack integration.

**Comment by vscheuber** [comment]
Won't do. Re-open if you see a strong need to change our use of arguments and options.
