### ISSUE TITLE
Add -D option to all commands to be able to specify directory for saving output. 

### ISSUE THREAD

**Issue by stephenpayne262** [rockcarver/frodo-cli#232]
**Is your feature request related to a problem? Please describe.**
I want to automate exporting all items that can be exported, but want each category to go in it's own Directory. The idm exportAllRaw supports an option -D to do this, but this isn't available across all the export commands. 

**Describe the solution you'd like**
Each command would support -D to specify the directory:
journey export
application export
email_tempates 
idp
saml
script
secret 
theme

**Comment by forgerock-dss** [comment]
-D should also be extended for import operations to specify a directory location of the source files

**Comment by vscheuber** [comment]
frodo-cli v2.0.0-23 and later support `-D` and `--directory` option across all export/import sub-commands.
