### ISSUE TITLE
Support no_proxy variable

### ISSUE THREAD

**Issue by BrenemanR** [rockcarver/frodo-cli#311]
## Allow frodo-cli to support the no_proxy environment variable
I've deployed frodo-cli on a linux machine using the pre-compiled binary. I see that https_proxy variable is supported, but is no_proxy also supported? I don't want these frodo commands to use the https_proxy variable, but I don't want to constantly unset that https_proxy variable if possible.

**Comment by vscheuber** [comment]
@BrenemanR did you test and it didn't work or are you asking if it should work? I have not tested the use of no_proxy but this [axios ticket](https://github.com/axios/axios/issues/434) implied that axios (the http framework Frodo uses) supports it since Nov 2019.

**Comment by BrenemanR** [comment]
I tested it and it did not work, but wanted to confirm if that was expected behavior. Thanks for the quick reply sharing the axios ticket. I tried testing using the below no_proxy varibable, but it appears to still use the https_proxy variable when making requests.

**export no_proxy=localhost,127.0.0.*,*.com**

I will look into the axios repo to see if there is anything indicating that I'm setting up the variables incorrectly. Thank you!

**Comment by vscheuber** [comment]
Hi @BrenemanR , did your research yield any further conclusions? Were you able to make it work?

**Comment by BrenemanR** [comment]
Hey @vscheuber , unfortunately I was not able to get the no_proxy variable working successfully. I've been using the the workaround of removing the https_proxy variable in order to make requests with Frodo. I'm guessing this is an issue with axios if Frodo is using that http framework, though.

**Comment by vscheuber** [comment]
Thank you, @BrenemanR , closing.
