### ISSUE TITLE
Three with Device Match Node : Custom Matching Script not exported

### ISSUE THREAD

**Issue by ijha9480** [rockcarver/frodo-cli#316]
## Frodo CLI version
1.0.1

## Describe the issue
Hello,

First, thanks for this awsome tool that simplify our deployment !

In our three we use a device match node with a custom matching script .
The problem is that frodo does not export the script related in the node , so when we import the journey there is an error related to the Device Match Node.

Regards

**Comment by vscheuber** [comment]
@ijha9480 confirmed. I have a fix ready to go for the 2.x branch, not for 1.x, though. Let me know if that works for you. We are looking to release 2.0.0 in the coming weeks, it's been in pre-release state for a while now. You'll see this issue close when I check-in and build the fix. Feel free to re-open and ask for a 1.x fix if you don't see yourself moving to 2.x any time soon.

**Comment by vscheuber** [comment]
@ijha9480 the fix is available in [Release - Frodo CLI 2.0.0-29](https://github.com/rockcarver/frodo-cli/releases/tag/v2.0.0-29).
