### ISSUE TITLE
Loop in prune option

### ISSUE THREAD

**Issue by Dominique88** [rockcarver/frodo-cli#322]
Hello I have a problem with prune option. 

## Frodo CLI version
C:\_W\_Tools\frodo>frodo -v
You are running the binary release.
Installed versions:
cli: v2.0.0-30
lib: v2.0.0-48
node: v18.5.0

## Describe the issue
When I use prune I can't answer the question y/n.

TokenCacheOps.getTokenCachePath: end [tokenCachePath=C:\Users\IDPO3980/.frodo/TokenCache.json]
TokenCacheOps.readToken: found userSession token in cache [expires in 1798s]
| 187 total nodesTokenCacheOps.hasToken: end [has userSession token: true]
TokenCacheOps.readToken: start
TokenCacheOps.getTokenCachePath: start
TokenCacheOps.getTokenCachePath: end [tokenCachePath=C:\Users\IDPO3980/.frodo/TokenCache.json]
TokenCacheOps.readToken: found userSession token in cache [expires in 1798s]
√ 196 total nodes
√ 106 active nodes
√ 90 orphaned nodes
Prune (permanently delete) orphaned nodes? (y|n): AuthenticateOps.getUserSessionToken: cached
TokenCacheOps.saveUserSessionToken: start
TokenCacheOps.getTokenCachePath: start
TokenCacheOps.getTokenCachePath: end [tokenCachePath=C:\Users\IDPO3980/.frodo/TokenCache.json]
TokenCacheOps.purgeExpiredTokens: start [now=1700149913226]
TokenCacheOps.purgeExpiredTokens: end
TokenCacheOps.saveUserSessionToken: token alreaday in cache

Best regards.
Dominique

**Comment by Dominique88** [comment]
I can' reply y or n.

Prune (permanently delete) orphaned nodes? (y|n): AuthenticateOps.getUserSessionToken: cached

**Comment by Dominique88** [comment]
![image](https://github.com/rockcarver/frodo-cli/assets/77063807/c7edf364-549f-4088-8fd6-046a486bbe26)

**Comment by vscheuber** [comment]
Hi @Dominique88 , I tried to replicate what you are seeing but I cannot. I tried on windows, using the same version:
```
>frodo -v
You are running the binary release.
Installed versions:
cli: v2.0.0-30
lib: v2.0.0-48
node: v18.5.0
```
and everything appears to be running fine:
```
>frodo journey prune frodo-dev
Connected to https://openam-frodo-dev.forgeblocks.com/am [alpha] as user vscheuber@gmail.com
√ 800 total nodes
√ 78 active nodes
√ 722 orphaned nodes
Prune (permanently delete) orphaned nodes? (y|n): y
^C==-------------------------------------] 6% | 46/722 | Removing b47756c2-7ccd-47fb-9201-6a7a15d1dd66...
```

What concerns me about your output is that it appears your clock is running unnaturally fast! You should see these `Connected to http://localhost:7080/connexion [employeur] as user amadmin` only when your session is about to expire. Either your system has configured an unnaturally short session lifetime (seconds?) or you are running inside a VM with a racing clock (probably more likely).

Can you think of anything in your environment (AM server or your desktop running frodo) that would explain the effects you are seeing?

**Comment by Dominique88** [comment]
Thank you for your reply.
I will investigate more.

**Comment by vscheuber** [comment]
Closing for now. @Dominique88 please re-open if you feel this is something we need to look into more.
