### ISSUE TITLE
Add ability to specify IDM URL when adding a connection profile

### ISSUE THREAD

**Issue by rohithkk** [rockcarver/frodo-cli#359]
## Describe the solution you'd like
When adding a new connection profile, we specify the host for the AM deployment. If the deployment is detected as ForgeOps deployment, when exporting a journey, Frodo tries to export the theme by constructing the IDM URL from the AM URL that is passed. In deployments where IDM is on a different load balanced URL, this request throws 404 error causing frodo to exit the export operation. 

It would be beneficial if we can explicitly provide the complete idm URL when adding the profile as shown below so that frodo can fetch resources from each component correctly.

`frodo conn add -k https://myam.com/am --idm-host https://myidm.com/openidm XXXX YYYY`

**Comment by vscheuber** [comment]
@rohithkk check out [Frodo CLI 2.0.6-0](https://github.com/rockcarver/frodo-cli/releases/tag/v2.0.6-0) and see if that addresses your ask:

### Added

  - Improve support for custom platform deployments (non-forgeops or customized forgeops)
    
      - \#429: Added options to support custom oauth2 clients used to obtain the access token for IDM API calls:
        
          - `--login-client-id <client-id>` Specify a custom OAuth2 client id to use a your own oauth2 client for IDM API calls in deployments of type "cloud" or "forgeops". Your custom client must be configured as a public client and allow the authorization code grant using the "openid fr:idm:\*" scope. Use the "--redirect-uri" parameter if you have configured a custom redirect uri (default: "<host>/platform/appAuthHelperRedirect.html").
          - `--login-redirect-uri <redirect-uri>` Specify a custom redirect URI to use with your custom OAuth2 client (efault: "<host>/platform/appAuthHelperRedirect.html").
        
        The above options can also be supplied through environment variables:
        
          - `FRODO_LOGIN_CLIENT_ID` OAuth2 client id for IDM API calls. Overridden by '--login-client-id' option.
          - `FRODO_LOGIN_REDIRECT_URI` Redirect Uri for custom OAuth2 client id. Overridden by '--login-redirect-uri' option.
    
      - \#359: Added an option to support custom IDM host URLs for all IDM API calls (e.g. platform deployments hosting AM and IDM on/in different DNS hosts/domains):
        
          - `--idm-host <idm-host>` IDM base URL, e.g.: <https://cdk.idm.example.com/myidm>. Use only if your IDM installation resides in a different domain and/or if the base path differs from the default "/openidm".
        
        The above option can also be supplied through an environment variable:
        
          - `FRODO_IDM_HOST` IDM base URL. Overridden by '--idm-host' option.
    
    ***Note:*** All the above options are also persisted in connection profiles so they only have to specified once and after that they come out of the connection profile.
