### ISSUE TITLE
Doing a full export of IDM from FIDC started hanging between v2.0.0.32 and v2.0.0.33

### ISSUE THREAD

**Issue by dbalmain** [rockcarver/frodo-cli#363]
## Frodo CLI version
You are running the NPM package.
Installed versions:
cli: v2.0.0-33
lib: v2.0.0-49
node: v18.18.2

## Describe the issue
Doing a full export of IDM from FIDC started hanging between v2.0.0.32 and v2.0.0.33.

```
➜ npm i -g @rockcarver/frodo-cli@v2.0.0-33

changed 225 packages in 4s

38 packages are looking for funding
  run `npm fund` for details

customerone-fidc-config on  main [!?] via  v18.18.2 took 4s 
➜ frodo idm export dev -A -D ./idm
Connected to https://openam-tfs-anz-dev.id.forgerock.io/am [alpha] as service account Frodo-SA]

# <== this hangs here indefinitely

customerone-fidc-config on  main [!?] via  v18.18.2 took 9s 
➜ npm i -g @rockcarver/frodo-cli@v2.0.0-32

changed 225 packages in 4s

38 packages are looking for funding
  run `npm fund` for details

customerone-fidc-config on  main [!?] via  v18.18.2 took 4s 
➜ frodo idm export dev -A -D ./idm
Connected to https://openam-tfs-anz-dev.id.forgerock.io/am [alpha] as service account Frodo-SA]
✔ Exported config objects.
```

Other exports work for me without any issues. It seems to just be the IdM export.

**Comment by vscheuber** [comment]
@dbalmain I have been able to reproduce some weird behavior (not exactly what you reported but very similar) and will look into this more. Could you maybe try with the latest pre-release? We are getting really close to releasing 2.0.0 but this one is a must fix for sure!

FYI @atomicsamurai @phalestrivir if anyone of you gets to this before I do, please claim the issue.

**Comment by dbalmain** [comment]
@vscheuber, thanks for looking into this. It's still happening on the latest version. It's been stuck here for about 5-minutes;
![image](https://github.com/rockcarver/frodo-cli/assets/4016/5fb89c3b-bf9f-4548-8861-6a82f1ec8e59)
