### ISSUE TITLE
Getting Service account login error: Error: self-signed certificate in certificate chain

### ISSUE THREAD

**Issue by greytower** [rockcarver/frodo-cli#371]
When trying to use the info option I keep getting the self signed certficate error even when using the -k option
have tried removing frodo completely and then   
Tapping brew and re isntalling but it still does not resolve the isuse.
[debug.log](https://github.com/rockcarver/frodo/files/14269977/debug.log)

 
~ frodo info openam-availity-use1-dev  -k
Error getting cookie name: Error: self-signed certificate in certificate chain
Service account login error: Error: self-signed certificate in certificate chain

**Comment by vscheuber** [comment]
@greytower please check out this solution discussed in another [issue #215]( https://github.com/rockcarver/frodo-cli/issues/215#issuecomment-1480165473).

We had several similar reports all of which ended up resolving using the solution described in the link above. Note: the `-k` option should work in most cases when the connection between frodo and the FR platform is direct. However, the `-k` option typically does not work when outgoing network proxies are in play, which terminate SSL on their side and then need to trust the untrusted certs themselves or use self-signed certs.

**Comment by vscheuber** [comment]
Appears to be abandoned. Please re-open if this is still an issue.
