### ISSUE TITLE
Getting certificate error while trying to make connection

### ISSUE THREAD

**Issue by navjyot058** [rockcarver/frodo-cli#400]
## Frodo CLI version
Provide output of `frodo -v`

vboxuser@Forgerock:~$ frodo -v
You are running the binary release.
Installed versions:
cli: v2.0.0-64
lib: v2.0.0-88
node: v20.11.1

## Describe the issue
A clear and concise description of what the issue is.

I have installed frodo in my forgeops deployment in my ubuntu machine.
However, when i am trying make connection, i get the below cert error.
can anyone help?

vboxuser@Forgerock:~$ frodo conn add https://forgeops.example.com/am john.doe@company.com ''
Error getting tokens
  self-signed certificate

**Comment by vscheuber** [comment]
@navjyot058 please try to use the `-k`, `--insecure` switch: Allow insecure connections when using SSL/TLS. Has no effect when using a network proxy for https (HTTPS_PROXY=http://<host>:<port>), in that case the proxy must provide this capability. (default: Don't allow insecure connections)

To see all the command options for a command, use `-h`:
`frodo conn save -h`

Please let me know if that works for you.

**Comment by navjyot058** [comment]
@vscheuber , Thanks for looking into this.
I tried passing the argument, but it is still complaining.

vboxuser@Forgerock:~/forgeops$ frodo conn add https://forgeops.example.com/am/ amadmin ' ' --insecure
Error getting tokens
  self-signed certificate

**Comment by navjyot058** [comment]
vboxuser@Forgerock:~/forgeops$ frodo conn add -k  https://forgeops.example.com/am/ amadmin 'zIiolyo9gdjpnssPQwAedeNh'
Error getting tokens
  self-signed certificate
vboxuser@Forgerock:~/forgeops$ frodo conn save -k  https://forgeops.example.com/am/ amadmin 'zIiolyo9gdjpnssPQwAedeNh'
Error getting tokens
  self-signed certificate
vboxuser@Forgerock:~/forgeops$ frodo conn save --insecure  https://forgeops.example.com/am/ amadmin 'zIiolyo9gdjpnssPQwAedeNh'
Error getting tokens
  self-signed certificate

**Comment by vscheuber** [comment]
@navjyot058 I have confirmed your issue and I am working on a fix. Please stay tuned and I will notify you when it's ready.

**Comment by vscheuber** [comment]
@navjyot058 please give [Frodo CLI 2.0.0-66](https://github.com/rockcarver/frodo-cli/releases/tag/v2.0.0-66) a try and let me know if that does not resolve your issue.

**Comment by Harshdeepahuja** [comment]
Thanks @vscheuber for fixing the connection issue. looks like we might need same fix on frodo logs as well 

vboxuser@vboxuser-VMware-Virtual-Platform:~/Documents/workspace$ frodo logs  tail -l 4 -c -k  https://forgeops.example.com |sed 's/\\n/\n/g' |sed 's/\\t/\t/g' > /home/vboxuser/Documents/workspace/log1.txt 
Found admin credentials in connection profile, attempting to create log api credentials...
Error getting tokens
  self-signed certificate
Unable to create log api credentials.
No log api credentials found!

cc @navjyot058

**Comment by vscheuber** [comment]
@Harshdeepahuja that's an interesting observation! Clearly the fix doesn't appear to work for the `logs` command but at the same time, the `logs` is a cloud-only command. ForgeOps or other deployments do not provide the same logging endpoints as PingOne Advanced Identity Cloud does.

Check out this [chapter in the ForgeOps documentation](https://backstage.forgerock.com/docs/forgeops/7.5/troubleshoot/pods.html) how to obtain logs in a ForgeOps deployment.

**Comment by Harshdeepahuja** [comment]
Thanks @vscheuber for the clarification. I have been using debug-logs and it works fine. Thanks again for help.
