### ISSUE TITLE
javascripts outside json file.

### ISSUE THREAD

**Issue by jeffreyvangorkum** [rockcarver/frodo-cli#52]
When Frodo exports the scripts, they get put in either separate json files or one big json file. From a CI/CD perspective this isn't the ideal situation. As it's not a javascript file, you cannot run automatic jobs on the code from a git perspective. Think about code quality control or cve scans or also editing java scripts from your IDE directly from a cloned git environment.

Is it an option to, next to exporting the script json, to create a file for the javascript alone as well? And when using the import option, a function that puts the javascript in the json file again?

**Comment by vscheuber** [comment]
I love the suggestion! This has come up several times in the past. We are debating possible options:

Introduce a new parameter to the `frodo script export` and `frodo script import` commands: `--external-source` (or something like that).

When supplying the paramater on export, frodo creates something like this:
```
<script name1>.json
<script name2>.js
<script name2>.json
<script name2>.groovy
```
where the .json file would look exactly the way it looks today (including the script source embedded in the json) and then there would be another file with the same filename prefix but a suffix according to the script language (`.js` or `.groovy`) containing only the script code.

When supplying the parameter on import, frodo will try to read the external source file and fallback on what's in the json file and print a warning.

On import the behavior is debatable: Should frodo error out if it cannot find an external script? Or should it silently fallback on what's in the json file.

**Comment by vscheuber** [comment]
@meesvandongen it looks like you are working on something along these lines in rockcarver/frodo-lib#179
